import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {createSharedStore} from './shared.mjs';
import {createServer} from './server.mjs';
function fixture(store){const s=store.snapshot();s.employees=[{id:1,name:'Test manager',role:'Manager',pin:'9876',active:1},{id:2,name:'Test staff',role:'Staff',pin:'1234',active:1}];s.inventory_items=[{id:1,product_name:'Test food',quantity_on_hand:20,unit:'portion',counted:1}];s.pos_products=[{id:1,name:'Test sandwich',category:'FOOD',price_cents:200,kitchen:1}];s.pos_recipes=[{id:1,product_id:1,item_id:1,quantity:1}];s.cash_drawers=[{id:1,opened_at:1,opened_by:1,opened_name:'Test manager',opening_cents:10000}];return s;}
function init(store){const r=store.handle('/shared/init','POST',{snapshot:fixture(store),pin:'9876'});assert.equal(r.status,200,JSON.stringify(r.body));return r.body;}
function sale(buzzer=''){return {key:crypto.randomUUID(),cart:[{product:{id:1,price:200,revision:0},quantity:1,note:'No onion'}],tendered:500,buzzer,note:'Test order'};}
test('several register sales share one drawer and stock, retries do not duplicate',()=>{const store=createSharedStore();try{init(store);const orders=[sale('12'),sale('13'),sale('14')];for(const o of orders)assert.equal(store.handle('/shared/checkout','POST',o).status,200);const repeat=store.handle('/shared/checkout','POST',orders[0]);assert.equal(repeat.body.id,1);const snapshot=store.snapshot();assert.equal(snapshot.sales.length,3);assert.equal(snapshot.cash_entries.reduce((n,x)=>n+x.amount_cents,0),600);assert.equal(snapshot.inventory_items[0].quantity_on_hand,17);assert.equal(store.handle('/shared/checkout','POST',sale('012')).status,400);assert.equal(store.snapshot().sales.length,3);const pub=store.handle('/shared/public','GET').body;assert.equal(pub.kitchen.length,3);assert.equal(pub.kitchen[0].total,0);assert.equal(pub.kitchen[0].items[0].price,0);assert.equal(pub.employees,undefined);}finally{store.close();}});
test('manager snapshot saves conflict with later sales; incorrect and staff PINs have no manager access',()=>{const store=createSharedStore();try{const m=init(store);assert.equal(store.handle('/shared/login','POST',{pin:'1234'}).status,400);assert.equal(store.handle('/shared/snapshot','GET').status,400);const snap=store.handle('/shared/snapshot','GET',{},m.session).body;store.handle('/shared/checkout','POST',sale());assert.equal(store.handle('/shared/save','POST',{key:crypto.randomUUID(),revision:snap.revision,snapshot:snap.snapshot},m.session).status,409);assert.equal(store.snapshot().sales.length,1);const current=store.handle('/shared/snapshot','GET',{},m.session).body;current.snapshot.pos_products[0].name='Updated sandwich';const body={key:crypto.randomUUID(),revision:current.revision,snapshot:current.snapshot};assert.equal(store.handle('/shared/save','POST',body,m.session).status,200);assert.equal(store.handle('/shared/save','POST',body,m.session).status,200);assert.equal(store.snapshot().sales.length,1);}finally{store.close();}});
test('kitchen status and employee punches are shared and validated',()=>{const store=createSharedStore();try{init(store);const r=store.handle('/shared/checkout','POST',sale('4')).body;assert.equal(store.handle('/shared/kitchen','POST',{id:r.id,expected:'NEW',next:'PREPARING'}).status,200);assert.equal(store.handle('/shared/public','GET').body.kitchen[0].status,'PREPARING');assert.equal(store.handle('/shared/kitchen','POST',{id:r.id,expected:'NEW',next:'READY'}).status,400);assert.equal(store.handle('/shared/clock','POST',{pin:'1234',clockIn:true}).status,200);assert.equal(store.handle('/shared/clock','POST',{pin:'1234',clockIn:true}).status,400);assert.equal(store.handle('/shared/clock','POST',{pin:'1234',clockIn:false}).status,200);assert.equal(store.snapshot().time_shifts.length,1);assert.ok(store.snapshot().time_shifts[0].clock_out);}finally{store.close();}});
test('records survive process reopen and bad imports roll back',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'barpos-shared-test-'));const filename=path.join(dir,'records.sqlite');let store=createSharedStore({filename});try{init(store);store.handle('/shared/checkout','POST',sale());store.close();store=createSharedStore({filename});assert.equal(store.snapshot().sales.length,1);const m=store.handle('/shared/login','POST',{pin:'9876'}).body;const s=store.handle('/shared/snapshot','GET',{},m.session).body;s.snapshot.pos_recipes[0].item_id=999;assert.equal(store.handle('/shared/save','POST',{key:crypto.randomUUID(),...s},m.session).status,400);assert.equal(store.snapshot().pos_recipes[0].item_id,1);assert.equal(store.snapshot().sales.length,1);}finally{store.close();fs.rmSync(dir,{recursive:true,force:true});}});
test('HTTP routes require the device token and work without an AI provider key',async()=>{const store=createSharedStore();const token='fake-shared-device-token-for-tests';const server=createServer({token,shared:store,key:''});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{const url='http://127.0.0.1:'+server.address().port;assert.equal((await fetch(url+'/shared/public')).status,401);const pub=await fetch(url+'/shared/public',{headers:{Authorization:'Bearer '+token}});assert.equal(pub.status,200);assert.equal((await pub.json()).ready,false);}finally{await new Promise(resolve=>server.close(resolve));store.close();}});
test('five concurrent HTTP register requests and their retries record five sales exactly',async()=>{const store=createSharedStore();init(store);const token='fake-shared-device-token-for-tests';const server=createServer({token,shared:store,key:''});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{const url='http://127.0.0.1:'+server.address().port;const orders=Array.from({length:5},(_,i)=>sale(String(i+1)));const responses=await Promise.all([...orders,...orders].map(async body=>{const response=await fetch(url+'/shared/checkout',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(body)});assert.equal(response.status,200);return response.json();}));assert.equal(new Set(responses.map(x=>x.id)).size,5);assert.equal(store.snapshot().sales.length,5);assert.equal(store.snapshot().cash_entries.reduce((n,x)=>n+x.amount_cents,0),1000);assert.equal(store.snapshot().inventory_items[0].quantity_on_hand,15);}finally{await new Promise(resolve=>server.close(resolve));store.close();}});
